/** Departments and rooms — seeded into PostgreSQL on first run. */

export const SEED_DEPARTMENTS = [
  { code: 'ADMIN', name_en: 'Administration', name_ar: 'الإدارة' },
  { code: 'FAC', name_en: 'Facilities', name_ar: 'المرافق' },
  { code: 'IT', name_en: 'IT Support', name_ar: 'دعم تقنية المعلومات' },
];

/** Rooms grouped by department code. */
export const SEED_ROOMS_BY_DEPT = {
  ADMIN: {
    '4S SUPPORT#1(SMALL CONFERENCE ROOM)': [
      'ROUND MEETING TABLE', 'CHAIRS WITH HEAD AND ARM REST', 'PROJECTOR WITH PROJECTOR SCREEN',
      'AC GREE 1.5 TON', 'DOOR', 'WINDOW', 'WINDOW CURTAIN', 'SMOKE DETECTOR',
      'CEILING LIGHTS 60x60', 'PB BOARD', 'DOUBLE SOCKET WITH SWITCH', 'SINGLE SWITCH',
      'INTERNET SOCKET', 'FIRE EXTINGUISHER ABC DRY POWDER 20LB',
    ],
    'MANAGERS ROOM': [
      'WORKSTATION COMPLETE SET 1 PERSON', 'CHAIRS WITH HEAD AND ARM REST', 'SMALL MEETING TABLE',
      'VISITOR CHAIR', 'REFRIGERATOR', 'FILE  CABINET', 'AC GREE 1.5 TON', 'DOOR', 'WINDOW',
      'SMOKE DETECTOR', 'SPOT CEILING LIGHTS', 'NESPRESSO COFFE MACHINE', 'FIRE EXTINGUISHER 20LB ABC',
    ],
    'PCC ROOM': [
      'WORKSTATION 12 SINGLE PERSON', 'CHAIRS WITH HEAD AND ARM REST', 'SINGLE PERSON SOFA', 'TEA TABLE',
      'AC GREE 1.5 TON', 'DOUBLE DOOR SET', 'SINGLE DOOR', 'LED TUBE LIGHTS', 'SPOT CEILING LIGHTS', 'PC',
      'CCTV CAMERA BULLET TYPE', 'PRINTER MACHINE', 'FACP BRAND SIMPLEX', 'HORN', 'MCP', 'SMOKE DETECTOR',
      'AED BOX', 'FIRE EXTINGUISHER ABC DRY POWDER 20LB', 'EXIT LIGHTS', 'WINDING MACHINE', 'LED BOARDS',
      'LED SCRENE 2.5X10M', 'ANDROID DISPLAY SCREEN SET', 'GATE PUNCHING MACHINE',
    ],
  },
  IT: {
    '4S R&D ROOM': [
      'WORKSTATION COMPLETE SET 2 PERSON', 'WORKSTATION COMPLETE SET 1 PERSON', 'CHAIRS WITH HEAD AND ARM REST',
      'AC GREE 1.5 TON', 'DOOR', 'WINDOW', 'WINDOW CURTAIN', 'SMOKE DETECTOR', 'CEILING LIGHTS 60x60',
      'DOUBLE SOCKET WITH SWITCH', 'SINGLE SWITCH', 'INTERNET SOCKET', 'PC', 'FIRE EXTINGUISHER ABC DRY POWDER 20LB',
    ],
    '4S R&D ROOM ONE PERSON (INSIDE)': [
      'WORKSTATION COMPLETE SET 1 PERSON', 'CHAIRS WITH HEAD AND ARM REST', 'FILE  CABINET 3 DOOR TYPE',
      'AC GREE 1.5 TON', 'DOOR', 'WINDOW', 'SMOKE DETECTOR', 'CEILING LIGHTS 60x60',
      'DOUBLE SOCKET WITH SWITCH', 'SINGLE SWITCH', 'INTERNET SOCKET', 'PC', 'PB SMALL',
    ],
    '4S SUPPORT# 2 ROOM': [
      'TABLELS COMPLETE SET', 'CHAIRS WITH HEAD AND ARM REST', 'AC GREE 1.5 TON', 'DOOR', 'WINDOW',
      'WINDOW CURTAIN', 'SMOKE DETECTOR', 'CEILING LIGHTS 60x60', 'DOUBLE SOCKET WITH SWITCH', 'SINGLE SWITCH',
      'INTERNET SOCKET', 'PC', 'IT CABINET', 'XEROX MACHINE', 'FILE CABINET DOUBLE DOOR',
    ],
  },
  FAC: {
    'PANTRY ROOM.': [
      'MAGNIFICA COFFE MACHINE', 'NESPRESSO COFFE MACHINE', 'GEEPAS COFFE MACHINE', 'ALSAIF COFFIE MACHINE',
      'OVEN', 'ELECTRICAL  KITTEL', 'CHAIRS WITH HEAD AND ARM REST',
    ],
    'GENETS TOILET ROOM': [
      'SPOT LIGHT', 'WASH BASIN', 'WATER CLOSET', 'HEAT DETECTOR', 'SOAF DISPENSER', 'TISSUE DISPENSER',
      'TISSUE HOLDER', 'EXHAUST FAN CEILING MOULDED',
    ],
    'LADIES TOILET ROOM': [
      'SPOT LIGHT', 'WASH BASIN', 'WATER CLOSET', 'HEAT DETECTOR', 'SOAF DISPENSER', 'TISSUE DISPENSER',
      'TISSUE HOLDER', 'EXHAUST FAN CEILING MOULDED',
    ],
    'SAFETY OFFICE ROOM': [
      'TABLE WITH COMPLETE SET 1 PERSON', 'CHAIRS', 'AC GREE 1.5 TON', 'DOUBLE DOOR', 'SMOKE DETECTOR',
      'SMALL SPOT CEILING LIGHTS', 'PANEL BOARAD', 'WATER DISPENSER', 'FLY CATCHER',
      'FIRE EXTINGUISHER 20LB ABC', 'FIRE EXTINGUISHER 20LB CO2',
    ],
  },
};
