/**
 * Login / WhatsApp directory — official main admins + camp sub-admins only.
 * Excel technician rows were removed so they are not re-seeded or shown as assignees.
 */
export const USERS = {
  'm.irfan': {
    username: 'm.irfan',
    name: 'Mohammad Irfan',
    phone: '+966530089716',
    role: 'admin',
    title: 'Civil Engineer',
    camp: 'All',
  },
  'abdulaziz.bq': {
    username: 'abdulaziz.bq',
    name: 'Abdulaziz Bin Quraya',
    phone: '+966535555844',
    role: 'admin',
    title: 'Facility and Maintenance Operations Manager',
    camp: 'All',
  },
  'ansar.basha': {
    username: 'ansar.basha',
    name: 'Ansar Basha',
    phone: '+966570822231',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'MGS BQ',
  },
  'shakir.sabir': {
    username: 'shakir.sabir',
    name: 'Shakir Hussain Sabir',
    phone: '+966598512638',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Madina Camp 1 BQ',
  },
  'shaik.rahmatullah': {
    username: 'shaik.rahmatullah',
    name: 'Shaik Rahmatullah',
    phone: '+966572399416',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Madina Camp 2 BQ',
  },
  'haja.fakruddin': {
    username: 'haja.fakruddin',
    name: 'Haja Fakruddin',
    phone: '+966530739703',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Juaymah Camp',
  },
  'jack.dhahran': {
    username: 'jack.dhahran',
    name: 'Jack',
    phone: '+966552650673',
    role: 'subadmin',
    title: 'Camp Sub-Admin — Dhahran Head Office',
    camp: 'Dhahran Camp',
  },
  'muzammil.khurais': {
    username: 'muzammil.khurais',
    name: 'Muzammil',
    phone: '+966562012614',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Khurais Camp',
  },
  'saroj.chettri': {
    username: 'saroj.chettri',
    name: 'Saroj Chettri',
    phone: '+966593327276',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'MGS PMT',
  },
  'aftab.ansari': {
    username: 'aftab.ansari',
    name: 'Aftab Shahid Ansari',
    phone: '+966570273731',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Madina Camp 2 PMT',
  },
  'hassan.ahmouda': {
    username: 'hassan.ahmouda',
    name: 'Hassan S Ahmouda',
    phone: '+966502760797',
    role: 'subadmin',
    title: 'Electrical Engineer',
    camp: 'Dhahran Camp',
  },
  'jose.mathew': {
    username: 'jose.mathew',
    name: 'Jose Mathew',
    phone: '+966551958361',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Dhahran Camp',
  },
  'mohamed.ekramuddin': {
    username: 'mohamed.ekramuddin',
    name: 'Mohamed Ekramuddin',
    phone: '+966510782025',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Madina Camp 3',
  },
  'nixon.estanislao': {
    username: 'nixon.estanislao',
    name: 'Nixon Agustin Estanislao',
    phone: '+966570751879',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Jubail Camp',
  },
  'aylwin.reginald': {
    username: 'aylwin.reginald',
    name: 'Aylwin Daniels Reginald',
    phone: '+966571027629',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Salasil Camp',
  },
  'muhammad.ansar': {
    username: 'muhammad.ansar',
    name: 'Muhammad Ansar',
    phone: '+966549096396',
    role: 'subadmin',
    title: 'Camp Sub-Admin',
    camp: 'Zuluf Camp',
  },
};

export default USERS;
