/** Auto-generated from MAINTAINENCE APP Excel + official staff. Do not edit by hand. */
export const USERS = {
  "mohammed": {
    username: "mohammed",
    name: "Mohammed Khalid",
    phone: "",
    role: "subadmin",
    title: "Electrician",
    camp: "TCF3 Camp",
  },
  "mohd": {
    username: "mohd",
    name: "Mohd Farhaz",
    phone: "",
    role: "subadmin",
    title: "Ac Technician",
    camp: "TCF3 Camp",
  },
  "umar": {
    username: "umar",
    name: "Umar Hayyat",
    phone: "",
    role: "subadmin",
    title: "Genrator Opretor",
    camp: "TCF3 Camp",
  },
  "mustaq": {
    username: "mustaq",
    name: "Mustaq Alam",
    phone: "",
    role: "subadmin",
    title: "Plumber",
    camp: "TCF3 Camp",
  },
  "abdulrhman": {
    username: "abdulrhman",
    name: "Abdulrhman Abdulstar",
    phone: "",
    role: "admin",
    title: "Maintenance Supervisor",
    camp: "All",
  },
  "munna": {
    username: "munna",
    name: "Munna Ansari",
    phone: "",
    role: "subadmin",
    title: "Electrician",
    camp: "Madina Camp 1 PMT",
  },
  "noor": {
    username: "noor",
    name: "Noor Alam",
    phone: "",
    role: "subadmin",
    title: "Plumber",
    camp: "Madina Camp 1 PMT",
  },
  "pramod": {
    username: "pramod",
    name: "Pramod Kumar Thakur",
    phone: "",
    role: "subadmin",
    title: "Stp Plant Operator",
    camp: "Madina Camp 1 PMT",
  },
  "rijwan": {
    username: "rijwan",
    name: "Rijwan Mohd Ilyas",
    phone: "",
    role: "subadmin",
    title: "Carpenter",
    camp: "Madina Camp 1 PMT",
  },
  "mohdsadiq": {
    username: "mohdsadiq",
    name: "Mohd Sadiq",
    phone: "",
    role: "subadmin",
    title: "Ac Technician",
    camp: "Madina Camp 1 PMT",
  },
  "arthur": {
    username: "arthur",
    name: "Arthur Kevin",
    phone: "",
    role: "subadmin",
    title: "Foreman Welder",
    camp: "Madina Camp 1 PMT",
  },
  "edwin": {
    username: "edwin",
    name: "Edwin Besola",
    phone: "",
    role: "subadmin",
    title: "Fabricator/Welder",
    camp: "Madina Camp 1 PMT",
  },
  "kadeem": {
    username: "kadeem",
    name: "Kadeem Ahmed",
    phone: "",
    role: "subadmin",
    title: "Ac Techinician",
    camp: "Dhahran Camp",
  },
  "bharat": {
    username: "bharat",
    name: "Bharat Ram",
    phone: "",
    role: "subadmin",
    title: "Carpenter",
    camp: "Dhahran Camp",
  },
  "swajan": {
    username: "swajan",
    name: "Swajan Gouranga",
    phone: "",
    role: "subadmin",
    title: "Plumber",
    camp: "Dhahran Camp",
  },
  "nagendra": {
    username: "nagendra",
    name: "Nagendra Kumar",
    phone: "",
    role: "subadmin",
    title: "Asst. Electrician",
    camp: "Dhahran Camp",
  },
  "shafiur": {
    username: "shafiur",
    name: "Shafiur Rahman",
    phone: "",
    role: "subadmin",
    title: "Electrician",
    camp: "Jubail Camp",
  },
  "shiv": {
    username: "shiv",
    name: "Shiv Kumar Sah",
    phone: "",
    role: "subadmin",
    title: "Carpenter",
    camp: "Jubail Camp",
  },
  "barakat": {
    username: "barakat",
    name: "Barakat Ali",
    phone: "",
    role: "subadmin",
    title: "Mason",
    camp: "Jubail Camp",
  },
  "shahid": {
    username: "shahid",
    name: "Shahid Hassan Ghulam Hassan",
    phone: "",
    role: "subadmin",
    title: "Engineer",
    camp: "Jubail Camp",
  },
  "snauwar": {
    username: "snauwar",
    name: "Snauwar Hussain",
    phone: "",
    role: "subadmin",
    title: "Ac Technician",
    camp: "Jubail Camp",
  },
  "alfredo": {
    username: "alfredo",
    name: "Alfredo Tenorio",
    phone: "",
    role: "subadmin",
    title: "Plumber",
    camp: "Jubail Camp",
  },
  "asif": {
    username: "asif",
    name: "Asif Aziz",
    phone: "",
    role: "subadmin",
    title: "Plumber",
    camp: "Juaymah Camp",
  },
  "raj": {
    username: "raj",
    name: "Raj Kumar Shrestha Januka",
    phone: "",
    role: "subadmin",
    title: "General Technician",
    camp: "Juaymah Camp",
  },
  "sobin": {
    username: "sobin",
    name: "Sobin Sahani",
    phone: "",
    role: "subadmin",
    title: "Camp Boy",
    camp: "Juaymah Camp",
  },
  "sanjeeb": {
    username: "sanjeeb",
    name: "Sanjeeb Kumar Mandal",
    phone: "",
    role: "subadmin",
    title: "Camp Asst.",
    camp: "Juaymah Camp",
  },
  "faisal": {
    username: "faisal",
    name: "Faisal Jefaish H AlMansour",
    phone: "",
    role: "subadmin",
    title: "Hse Specialist",
    camp: "Juaymah Camp",
  },
  "mohdshahid": {
    username: "mohdshahid",
    name: "Mohd Shahid",
    phone: "",
    role: "subadmin",
    title: "Day Security",
    camp: "Juaymah Camp",
  },
  "manoj": {
    username: "manoj",
    name: "Manoj Ray",
    phone: "",
    role: "subadmin",
    title: "Security",
    camp: "Juaymah Camp",
  },
  "upendra": {
    username: "upendra",
    name: "Upendra Sah",
    phone: "",
    role: "subadmin",
    title: "Camp Boy",
    camp: "Juaymah Camp",
  },
  "jitendra": {
    username: "jitendra",
    name: "Jitendra Mahara",
    phone: "",
    role: "subadmin",
    title: "Camp Boy",
    camp: "Juaymah Camp",
  },
  "sunny": {
    username: "sunny",
    name: "Sunny Prasad Jayswal",
    phone: "",
    role: "subadmin",
    title: "Camp Boy/ Food Handler",
    camp: "Juaymah Camp",
  },
  "radhe": {
    username: "radhe",
    name: "Radhe Shyam Dangi",
    phone: "",
    role: "subadmin",
    title: "Stp Operator",
    camp: "Juaymah Camp",
  },
  "som": {
    username: "som",
    name: "Som Bahadur Hiski",
    phone: "",
    role: "subadmin",
    title: "Camp Boy",
    camp: "Juaymah Camp",
  },
  "ram": {
    username: "ram",
    name: "Ram Prasad Pandit",
    phone: "",
    role: "subadmin",
    title: "Camp Boy",
    camp: "Juaymah Camp",
  },
  "manojkumar": {
    username: "manojkumar",
    name: "Manoj Kumar Yadav",
    phone: "",
    role: "subadmin",
    title: "Laundry Boy",
    camp: "Juaymah Camp",
  },
  "birbal": {
    username: "birbal",
    name: "Birbal Kewat Subhash Kewat",
    phone: "",
    role: "subadmin",
    title: "Laundry Boy",
    camp: "Juaymah Camp",
  },
  "shambu": {
    username: "shambu",
    name: "Shambu Kumar Sha",
    phone: "",
    role: "subadmin",
    title: "Camp Boy",
    camp: "Juaymah Camp",
  },
  "sunil": {
    username: "sunil",
    name: "Sunil Sahani Tun",
    phone: "",
    role: "subadmin",
    title: "Camp Boy",
    camp: "Juaymah Camp",
  },
  "rabin": {
    username: "rabin",
    name: "Rabin Mahara Pargash Mahara",
    phone: "",
    role: "subadmin",
    title: "Camp Boy",
    camp: "Juaymah Camp",
  },
  "hassan": {
    username: "hassan",
    name: "Hassan M. Al Salat",
    phone: "",
    role: "subadmin",
    title: "Electrician",
    camp: "Juaymah Camp",
  },
  "arshe": {
    username: "arshe",
    name: "Arshe Alam Manjar Mian",
    phone: "",
    role: "subadmin",
    title: "Electrician",
    camp: "Juaymah Camp",
  },
  "nurudeen": {
    username: "nurudeen",
    name: "Nurudeen Alhassan",
    phone: "",
    role: "subadmin",
    title: "H.E. Operator",
    camp: "Juaymah Camp",
  },
  "richard": {
    username: "richard",
    name: "Richard",
    phone: "",
    role: "subadmin",
    title: "Crane Operator",
    camp: "Juaymah Camp",
  },
  "ajab": {
    username: "ajab",
    name: "Ajab Aziz",
    phone: "",
    role: "subadmin",
    title: "Electrician",
    camp: "Khurais Camp",
  },
  "zakir": {
    username: "zakir",
    name: "Zakir",
    phone: "",
    role: "subadmin",
    title: "Plumber",
    camp: "Khurais Camp",
  },
  "aftaab": {
    username: "aftaab",
    name: "Aftaab",
    phone: "",
    role: "subadmin",
    title: "Electrician",
    camp: "MGS BQ",
  },
  "mannu": {
    username: "mannu",
    name: "Mannu",
    phone: "",
    role: "subadmin",
    title: "Auto Electrician",
    camp: "MGS BQ",
  },
  "juvy": {
    username: "juvy",
    name: "Juvy",
    phone: "",
    role: "subadmin",
    title: "Plumber",
    camp: "MGS BQ",
  },
  "sanjip": {
    username: "sanjip",
    name: "Sanjip Chowdry",
    phone: "",
    role: "subadmin",
    title: "Civil",
    camp: "MGS BQ",
  },
  "mohammedshoukat": {
    username: "mohammedshoukat",
    name: "Mohammed Shoukat",
    phone: "",
    role: "subadmin",
    title: "Landscape",
    camp: "MGS BQ",
  },
  "alam": {
    username: "alam",
    name: "Alam Khan",
    phone: "",
    role: "subadmin",
    title: "Landscape",
    camp: "MGS BQ",
  },
  "m.irfan": {
    username: "m.irfan",
    name: "Mohammad Irfan",
    phone: "+966530089716",
    role: "admin",
    title: "Civil Engineer",
    camp: "All",
  },
  "abdulaziz.bq": {
    username: "abdulaziz.bq",
    name: "Abdulaziz Bin Quraya",
    phone: "+966535555844",
    role: "admin",
    title: "Facility and Maintenance Operations Manager",
    camp: "All",
  },
  "ansar.basha": {
    username: "ansar.basha",
    name: "Ansar Basha",
    phone: "+966570822231",
    role: "subadmin",
    title: "Camp Sub-Admin",
    camp: "MGS BQ",
  },
  "shakir.sabir": {
    username: "shakir.sabir",
    name: "Shakir Hussain Sabir",
    phone: "+966598512638",
    role: "subadmin",
    title: "Camp Sub-Admin",
    camp: "Madina Camp 1 PMT",
  },
  "shaik.rahmatullah": {
    username: "shaik.rahmatullah",
    name: "Shaik Rahmatullah",
    phone: "+966572399416",
    role: "subadmin",
    title: "Camp Sub-Admin",
    camp: "Madina Camp 2 BQ",
  },
  "haja.fakruddin": {
    username: "haja.fakruddin",
    name: "Haja Fakruddin",
    phone: "+966530739703",
    role: "subadmin",
    title: "Camp Sub-Admin",
    camp: "Juaymah Camp",
  },
  "jack.dhahran": {
    username: "jack.dhahran",
    name: "Jack",
    phone: "+966552650673",
    role: "subadmin",
    title: "Camp Sub-Admin",
    camp: "Dhahran Camp",
  },
  "muzammil.khurais": {
    username: "muzammil.khurais",
    name: "Muzammil",
    phone: "+966562012614",
    role: "subadmin",
    title: "Camp Sub-Admin",
    camp: "Khurais Camp",
  },
  "saroj.chettri": {
    username: "saroj.chettri",
    name: "Saroj Chettri",
    phone: "+966593327276",
    role: "subadmin",
    title: "Camp Sub-Admin",
    camp: "Dhahran Camp",
  },
};

export default USERS;
